# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 741a8d3d4215c07c53cec05d42799a386185853129abee845ddd60a74c007d01e8cb36b0514c5fbc2bf2aa44a295fc5e0ffb89a43fc32a6b0a4e66f099f6ec06

test:
  secret_key_base: 9514d23997730f7bd0f84dfb96b959c3ce40b8b58f86dcd816143fc84a00499fe5e714fab2ec2197cdbc4c653e3c3da2a5637881654565ae47eca8935d79fa87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
